import { Request, Response, NextFunction } from "express";
import { ApiErrorMessages as E } from "./errors";

type SequelizeModel = {
	getAttributes: () => Record<string, any>;
};

function isNil(value: unknown): boolean {
	return value === null || value === undefined;
}

function checkType(expected: any, value: unknown): boolean {
	const key = expected?.key ?? expected?.toString?.() ?? "";
	const t = String(key).toUpperCase();
	if (isNil(value)) return true;
	if (t.includes("STRING") || t.includes("TEXT") || t.includes("UUID") || t.includes("DATEONLY")) return typeof value === "string";
	if (t.includes("INTEGER") || t.includes("BIGINT") || t.includes("FLOAT") || t.includes("DOUBLE") || t.includes("DECIMAL")) return typeof value === "number";
	if (t.includes("BOOLEAN")) return typeof value === "boolean";
	if (t.includes("JSON")) return typeof value === "object";
	if (t.includes("DATE")) return typeof value === "string" || value instanceof Date;
	return true; // fallback: don't block unknown types
}

export function validateBody(model: SequelizeModel, opts: { partial: boolean; allowedFields?: string[] }) {
	return (req: Request, res: Response, next: NextFunction) => {
		try {
			const attrs = model.getAttributes?.() || {};
			const body = req.body || {};
			const errors: string[] = [];

			// Check allowed fields whitelist
			if (opts.allowedFields) {
				const bodyKeys = Object.keys(body);
				const invalidFields = bodyKeys.filter(key => !opts.allowedFields!.includes(key));
				if (invalidFields.length) {
					errors.push(`Disallowed fields: ${invalidFields.join(', ')}`);
				}
			}

			for (const [name, meta] of Object.entries(attrs)) {
				// skip auto fields
				if (meta.primaryKey || meta._autoGenerated || meta.autoIncrement) continue;
				
				// skip fields not in whitelist if provided
				if (opts.allowedFields && !opts.allowedFields.includes(name)) continue;
				
				const hasValue = Object.prototype.hasOwnProperty.call(body, name);
				const value = body[name];

				// required checks on create only (partial=false) when no default
				if (!opts.partial && meta.allowNull === false && isNil(meta.defaultValue)) {
					if (!hasValue || isNil(value)) errors.push(`Missing required field: ${name}`);
				}

				// type checks if provided
				if (hasValue && !checkType(meta.type, value)) {
					errors.push(`Invalid type for field: ${name}`);
				}
			}

			if (errors.length) return res.status(422).json({ message: E.VALIDATION_FAILED, errors });
			return next();
		} catch (e) {
			return res.status(422).json({ message: E.VALIDATION_FAILED });
		}
	};
}

export function getModelSchema(model: SequelizeModel) {
	const attrs = model.getAttributes?.() || {};
	const schema: any = {
		fields: {},
		required: [],
		types: {}
	};

	for (const [name, meta] of Object.entries(attrs)) {
		// skip auto fields
		if (meta.primaryKey || meta._autoGenerated || meta.autoIncrement) continue;

		schema.fields[name] = {
			type: meta.type?.toString() || 'unknown',
			allowNull: meta.allowNull !== false,
			defaultValue: meta.defaultValue
		};

		schema.types[name] = meta.type?.toString() || 'unknown';

		// required fields (for POST)
		if (meta.allowNull === false && isNil(meta.defaultValue)) {
			schema.required.push(name);
		}
	}

	return schema;
}


